Repository wecode-bootcamp-korea/34-1st-Wish-Korea-frontend, pull requests merged in 2022-06, with the labels that each got.

#7 [34기 우혜림 - 위시코리아] footer 레이아웃 2차 수정완료
  public/images/footImg.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 완료

#6 [34기 우혜림 - 위시코리아] Cart - 리뷰 반영 1차 수정
  .vscode/setting.json
  public/data/List.json
  public/images/bubble.png
  public/images/lovely.png
  public/images/not.png
  public/images/soap.png
  src/pages/ProductCart/ProductCart.js
  src/pages/ProductCart/ProductCart.scss
  src/pages/ProductCart/ProductCount.js
  src/pages/ProductCart/ProductCount.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#8 [34기 우혜림 - 위시코리아] Nav - 머지 후 브랜치 이름 변경 및 내용 수정
  public/data/Nav.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#11 [34기 우혜림 - 위시코리아] cart 불필요한 코드 제거
  src/pages/ProductCart/ProductCart.js
Labels: 멘토 리뷰 요청

#4 [34기 정예지 - 위시코리아] LIST : Add: 1차완성 : sider 내용 수정완료
  .vscode/settings.json
  public/data/detailsData.json
  public/data/listData.json
  public/images/add-to-cart.png
  public/images/heart.png
  public/images/heart_on.png
  public/images/list_img1.jpg
  public/images/list_img2.jpg
  public/images/vs1.jpg
  src/pages/Main/Main.js
  src/pages/ProductList/ProductCard.js
  src/pages/ProductList/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#5 [34기 안중영 - 위시코리아] 회원가입 css 최종수정
  src/pages/Join/Join.js
  src/pages/Join/Join.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청
